# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Add all toppers to the DB
Item.create([
    { name: 'Bobby Helmet' },
    { name: 'Brünnehilde' },
    { name: 'Cherry Top' },
    { name: 'Devil Horns' },
    { name: 'Fez' },
    { name: 'Fire Helmet' },
    { name: 'Gold Cap', rarity: Item.rarities[:limited] },
    { name: 'Halo' },
    { name: 'Hard Hat' },
    { name: 'Mariachi Hat' },
    { name: 'Pirate\'s Hat' },
    { name: 'Pizza Topper' },
    { name: 'Propellerhead' },
    { name: 'Royal Crown' },
    { name: 'Sombrero' },
    { name: 'Taxi Topper' },
    { name: 'Top Hat' },
    { name: 'Witch\'s Hat' },
    { name: 'Wizard Hat' },
    { name: 'Cavalier', rarity: Item.rarities[:premium] },
    { name: 'Locomotive', rarity: Item.rarities[:premium] },
    { name: 'Pixelated Shades', rarity: Item.rarities[:premium] },
    { name: 'Shark Fin', rarity: Item.rarities[:premium] },
    { name: 'Pumpkin', rarity: Item.rarities[:limited] },
    { name: 'Boombox', rarity: Item.rarities[:premium] },
    { name: 'Cow Skull', rarity: Item.rarities[:premium] },
    { name: 'Mohawk', rarity: Item.rarities[:premium] },
    { name: 'Portal - Cake' },
    { name: 'Blitzen', rarity: Item.rarities[:limited] },
    { name: 'Christmas Tree', rarity: Item.rarities[:limited] },
    { name: 'Sad Sapling', rarity: Item.rarities[:limited] },
    { name: 'Santa', rarity: Item.rarities[:limited] },
    { name: 'Unicorn', rarity: Item.rarities[:uncommon] },
    { name: 'Traffic Cone', rarity: Item.rarities[:uncommon] },
    { name: 'Tiara', rarity: Item.rarities[:uncommon] },
    { name: 'Shuriken', rarity: Item.rarities[:uncommon] },
    { name: 'Rhino Horns', rarity: Item.rarities[:uncommon] },
    { name: 'Mouse Trap', rarity: Item.rarities[:uncommon] },
    { name: 'Rasta', rarity: Item.rarities[:uncommon] },
    { name: 'Police Hat', rarity: Item.rarities[:uncommon] },
    { name: 'Plunger', rarity: Item.rarities[:uncommon] },
    { name: 'Paper Boat', rarity: Item.rarities[:uncommon] },
    { name: 'Gradutation Cap', rarity: Item.rarities[:uncommon] },
    { name: 'Bowler', rarity: Item.rarities[:uncommon] },
    { name: 'Fruit Hat', rarity: Item.rarities[:uncommon] },
    { name: 'Brodie Helmet', rarity: Item.rarities[:uncommon] },
    { name: 'Homburg', rarity: Item.rarities[:uncommon] },
    { name: 'Brown Derby', rarity: Item.rarities[:uncommon] },
    { name: 'Deerstalker', rarity: Item.rarities[:uncommon] },
    { name: 'Deadmau5', rarity: Item.rarities[:uncommon] },
    { name: 'Cockroach', rarity: Item.rarities[:uncommon] },
    { name: 'Chef\'s Hat', rarity: Item.rarities[:uncommon] },
    { name: 'Chainsaw', rarity: Item.rarities[:uncommon] },
    { name: 'Captain\s Hat', rarity: Item.rarities[:uncommon] },
    { name: 'Work Boot', rarity: Item.rarities[:uncommon] },
    { name: 'Birthday Cake', rarity: Item.rarities[:uncommon] },
    { name: 'Biker Cap', rarity: Item.rarities[:uncommon] },
    { name: 'Red Beret', rarity: Item.rarities[:uncommon] },
    { name: 'Antlers', rarity: Item.rarities[:uncommon] },
    { name: 'Season 1 - Bronze', rarity: Item.rarities[:limited] },
    { name: 'Season 1 - Silver', rarity: Item.rarities[:limited] },
    { name: 'Season 1 - Gold', rarity: Item.rarities[:limited] },
    { name: 'Season 1 - Platinum', rarity: Item.rarities[:limited] },
    { name: 'Robo-Visor', rarity: Item.rarities[:rare] },
    { name: 'Wildcat Ears', rarity: Item.rarities[:rare] },
    { name: 'Drink Helmet', rarity: Item.rarities[:rare] },
    { name: 'Pigeon', rarity: Item.rarities[:uncommon] },
    { name: 'Bow', rarity: Item.rarities[:uncommon] },
    { name: 'Cowboy Hat', rarity: Item.rarities[:uncommon] },
    { name: 'Flat Hat', rarity: Item.rarities[:uncommon] },
    { name: 'Golf Hat', rarity: Item.rarities[:uncommon] },
    { name: 'Light Bulb', rarity: Item.rarities[:uncommon] },
    { name: 'Party Hat', rarity: Item.rarities[:uncommon] },
    { name: 'Trucker Hat', rarity: Item.rarities[:uncommon] },
    { name: 'Visor', rarity: Item.rarities[:uncommon] },
    { name: 'White Hat', rarity: Item.rarities[:uncommon] },
    { name: 'Baseball Cap [F]', rarity: Item.rarities[:uncommon] },
    { name: 'Baseball Cap [B]', rarity: Item.rarities[:uncommon] },
])
